package test.greenDAO.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

import java.util.Date;

/**
 * Entity mapped to table "things".
 */
public class Duty implements Parcelable {

    private Long id;
    /** Not-null value. */
    private String title;
    private String info;
    private String type;
    private Boolean status;
    private java.util.Date date;

    public Duty() {
    }

    public Duty(Long id) {
        this.id = id;
    }

    public Duty(Long id, String title, String info, String type, Boolean status, java.util.Date date) {
        this.id = id;
        this.title = title;
        this.info = info;
        this.type = type;
        this.status = status;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.title);
        dest.writeString(this.info);
        dest.writeString(this.type);
        dest.writeValue(this.status);
        dest.writeLong(this.date != null ? this.date.getTime() : -1);
    }

    protected Duty(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.title = in.readString();
        this.info = in.readString();
        this.type = in.readString();
        this.status = (Boolean) in.readValue(Boolean.class.getClassLoader());
        long tmpDate = in.readLong();
        this.date = tmpDate == -1 ? null : new Date(tmpDate);
    }

    public static final Parcelable.Creator<Duty> CREATOR = new Parcelable.Creator<Duty>() {
        @Override
        public Duty createFromParcel(Parcel source) {
            return new Duty(source);
        }

        @Override
        public Duty[] newArray(int size) {
            return new Duty[size];
        }
    };
}
